# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2021 Krzysztof Kozlowski
# Author: Krzysztof Kozlowski <k.kozlowski.k@gmail.com>
#                             <krzk@kernel.org>
---
- name: Setup the user account
  import_tasks: setup-user.yml
- name: Setup the Python sandbox
  import_tasks: setup-python-sandbox.yml
- name: Setup the kernel builds environment
  import_tasks: setup-kernel-builds.yml
- name: Setup the Yocto builds environment
  import_tasks: setup-builds-yocto.yml
- name: Setup the worker
  import_tasks: setup-worker.yml
