# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2021,2025 Krzysztof Kozlowski
# Author: Krzysztof Kozlowski <k.kozlowski.k@gmail.com>
#                             <krzk@kernel.org>
---
- name: Setup the user account
  import_tasks: setup-user.yml
- name: Setup the build storage
  import_tasks: setup-build-storage.yml
- name: Setup the worker
  import_tasks: setup-worker.yml
