# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2021-2025 Krzysztof Kozlowski
# Author: Krzysztof Kozlowski <krzk@kernel.org>
---
- name: Check requirements for variables
  assert:
    that: item is defined
  with_items:
    - buildbot_user

- name: Update apt-cache
  apt:
    update_cache: yes
  tags: packages
  become: yes
  become_user: root
  when: ansible_facts['os_family'] == 'Debian'

- name: Install dependencies
  apt:
    name:
      - build-essential
      - chrpath
      - diffstat
      - gawk
      - git
      - pseudo
      - texinfo
      - psmisc
    state: present
  tags: packages, python
  become: yes
  become_user: root
  when: ansible_facts['os_family'] == 'Debian'
