---
- name: Check requirements for variables
  assert:
    that: '{{ item }} is defined'
  with_items:
    - buildbot_sandbox
    - buildbot_user
    - python_sandbox_version

- name: Update apt-cache
  apt:
    update_cache: yes
  tags: packages
  become: yes
  become_user: root
  when: ansible_facts['os_family'] == 'Debian'

- name: Install dependencies
  apt:
    name:
      - virtualenv
      - python3-dev
      # Setuptools needed for ansible pip
      - python-setuptools
    state: present
  tags: packages, python
  become: yes
  become_user: root
  when: ansible_facts['os_family'] == 'Debian'

- name: Create vitualenv sandbox
  command: virtualenv --python={{ python_sandbox_version }} {{ buildbot_sandbox }}
  args:
    creates: '{{ buildbot_sandbox }}'
  remote_user: '{{ buildbot_user }}'

- name: Check if sandbox is working
  shell:
    cmd: |
      set -eE
      source {{ buildbot_sandbox }}/bin/activate
      printenv | grep VIRTUAL
  args:
    executable: /bin/bash
  # Command does not change system so run it always (even in --check)
  check_mode: no
  changed_when: no
  remote_user: '{{ buildbot_user }}'

- name: Update PIP/Setuptools
  pip:
    name:
      - pip
      - setuptools
    state: latest
    virtualenv: '{{ buildbot_sandbox }}'
  remote_user: '{{ buildbot_user }}'
