# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2019-2024 Krzysztof Kozlowski
# Author: Krzysztof Kozlowski <k.kozlowski.k@gmail.com>
#                             <krzk@kernel.org>
---
- name: Include vars
  include_vars:
    file: ~/etc/ansible/vars/gate.yml

- name: Check requirements for variables
  assert:
    that: item is defined
  with_items:
    - authorized_keys_gate
    - ssh_allow_group
    - user_gate

- name: Create gateway unprivileged user
  user:
    name: '{{ user_gate }}'
    shell: /usr/sbin/nologin
    home: '/home/{{ user_gate }}'
    state: present
    create_home: yes
    password_lock: yes
    force: no
    generate_ssh_key: no
    append: no
    groups: '{{ ssh_allow_group }}'
  become: yes
  become_user: root

- name: Add to authorized keys - current key
  ansible.posix.authorized_key:
    user: '{{ user_gate }}'
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
    - "{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}"
    - "{{ lookup('env','HOME') + '/.ssh/id_ed25519.pub' }}"
  become: yes
  become_user: root

- name: Add to authorized keys - all keys
  ansible.posix.authorized_key:
    user: '{{ user_gate }}'
    state: present
    key: '{{ item }}'
  with_file: '{{ authorized_keys_gate }} '
  become: yes
  become_user: root
