# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2022 Krzysztof Kozlowski
# Author: Krzysztof Kozlowski <k.kozlowski.k@gmail.com>
#                             <krzk@kernel.org>
---
mail_foward_to: buildbot
path_mirror_repos: /var/lib/mirror
