#!/bin/bash -eu
#
# git-build-kernel cleanup script
#
# Removes gbk working directories (/tmp/kernel-<user>-<hash>-<random>) that are
# older than x days.
#

function usage()
{
	cat <<EOF
Usage: gbk-cleanup [-a AGE] [-d] [-h] [-u USER]

Delete gbk build directories /tmp/kernel-<user>-<hash>-<random>/ of user USER
that are older than AGE days.

Options:
  -a, --age AGE    Directories older than AGE days will be deleted. AGE must be
                   a positive real number. If not set, AGE defaults to 30 (days).
  -d, --dry-run    Do a dry-run only, i.e., don't delete anything.
  -h, --help       Show this help text.
  -u, --user USER  The name of the user whose directories are to be deleted. If
                   not set, all existing user directories (older than AGE days)
                   will be deleted.
EOF
}

# Directories older than AGE days will be deleted.
AGE=30

# Do a dry-run only, i.e., don't delete anything.
DRY_RUN=0

# Directories owned by USER will be deleted. If not set, the directories of
# all users will be deleted.
USER=

# Timestamp runs for logging.
TIMESTAMP=0

while [ $# -gt 0 ] ; do
	case "${1}" in
		-a|--age)
			shift
			AGE=${1}
			;;
		-d|--dry-run)
			DRY_RUN=1
			;;
		-h|--help)
			usage
			exit
			;;
		-u|--user)
			shift
			USER=${1}
			;;
		--timestamp)
			TIMESTAMP=1
			;;
		*)
			usage
			exit 2
			;;
	esac
	shift
done

[ "$TIMESTAMP" -eq 1 ] && echo "gbk-cleanup: start $(date)" || true

while IFS= read -r dir ; do
	# Paranoia: Verify that the directory name starts with /tmp/
	if [ "${dir#/tmp/}" = "${dir}" ] ; then
		continue
	fi

	# Extract the username from the directory name
	user=${dir#/tmp/kernel-}
	user=${user%%-*}

	# Delete the directory only if the user owns it
	if [ "$(stat --format='%U' "${dir}")" = "${user}" ] && \
	   [ "${USER:-${user}}" = "${user}" ] ; then
		if [ "${DRY_RUN}" -eq 1 ] ; then
			echo "gbk-cleanup: *Not* deleting ${dir} (dry-run)"
		else
			echo "gbk-cleanup: Deleting ${dir}"
			rm -rf "${dir}"
		fi
	fi
done < <(find /tmp -mindepth 1 -maxdepth 1 -type d -mtime "+${AGE}" \
			  -name 'kernel-*-*-*')

[ "$TIMESTAMP" -eq 1 ] && echo "gbk-cleanup: end $(date)" || true
