---
- name: Include vars
  include_vars:
    file: ~/etc/ansible/vars/tunnel.yml

# Need to get required vars also for delegated hosts
- name: Include vars
  include_vars:
    file: ~/etc/ansible/vars/tunnel.yml
  delegate_to: '{{ host_gate_ssh }}'
  delegate_facts: true

- name: Check requirements for variables
  assert:
    that: '{{ item }} is defined'
  with_items:
  - host_gate
  - host_gate_ssh
  - port_buildbot
  - port_gate
  - port_tunnel_on_gate
  - pubkey_gate
  - user_gate
  - user_tunnel

- name: Set environment for Debian
  set_fact:
    ssh_cmd: "/usr/bin/ssh"
  when: ansible_os_family == "Debian"

- name: Set environment for ArchLinux
  set_fact:
    ssh_cmd: "/usr/sbin/ssh"
  when: ansible_os_family == "Archlinux"

- name: Create unprivileged user for making tunnel
  user:
    name: '{{ user_tunnel }}'
    shell: /bin/bash
    home: '/home/{{ user_tunnel }}'
    state: present
    create_home: yes
    force: no
    generate_ssh_key: yes
    # SSH logins not allowed
    append: no
    groups: ''
  become: yes
  become_user: root

- name: Get public SSH key
  command: /bin/cat /home/{{ user_tunnel }}/.ssh/id_rsa.pub
  register: ssh_public_key
  check_mode: no
  changed_when: no
  become: yes
  become_user: root

# Only for debug. No need to print it as registering at gate happens in playbook here.
- debug:
    msg:
      - 'SSH public key for user {{ user_tunnel }}:'
      - '{{ ssh_public_key.stdout_lines }}'

- name: Deploy key to gate
  ansible.posix.authorized_key:
    user: '{{ user_gate }}'
    key: '{{ ssh_public_key.stdout }}'
  delegate_to: '{{ host_gate_ssh }}'
  remote_user: '{{ user_gate }}'
  # Ansible has trouble with concurrent steps on one machine -> gate,
  # so only one key is being stored eventually (last step overwrites).
  # Throttling solves the problem.
  throttle: 1

- debug:
    msg:
      - 'Manually remove old keys from any replaced hosts!'

- name: Set chmod on user's home directory
  file:
    path: '/home/{{ user_tunnel }}'
    mode: 0700
  become: yes
  become_user: root

# TODO: after migrating to Ansible v2.6, use user:password_lock
- name: Lock user password
  command: passwd -l {{ user_tunnel }}
  become: yes
  become_user: root

# Pubkey retrieved with: ssh-keyscan -H -p PORT HOSTNAME IP
- name: Add server to known hosts
  known_hosts:
    name: '{{ host_gate }}'
    state: present
    key: "{{ lookup('file', pubkey_gate) }}"
  become: yes
  become_user: '{{ user_tunnel }}'

- name: Install SystemD unit file
  template:
    src: tunnel.service.j2
    dest: /etc/systemd/system/tunnel.service
    mode: 0644
  become: yes
  become_user: root
  register: systemd_service

- name: Systemd reload
  systemd:
    daemon_reload: yes
  become: yes
  become_user: root
  when: systemd_service.changed | default(False)

- name: Systemd enable service
  systemd:
    name: tunnel.service
    enabled: yes
    masked: no
    state: restarted
  become: yes
  become_user: root
  when: systemd_service.changed | default(False)
