/*
 * https://groups.google.com/g/syzkaller/c/uj-hx-eBQ28/m/KCztJ2z6EAAJ
 */

// autogenerated by syzkaller (http://github.com/google/syzkaller)
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/syscall.h>
#include <unistd.h>

#include <linux/nfc.h>
#include <pthread.h>

int fd;

void *thr(void *arg)
{
	struct sockaddr_nfc_llcp sa;

	fprintf(stderr, "%s:%d\n", __func__, __LINE__);
	sa.sa_family = AF_NFC;
	sa.dev_idx = 0;
	sa.target_idx = 0x24a8;
	sa.nfc_protocol = 0;
	sa.dsap = 0;
	sa.ssap = 2;
	sa.service_name[0] = 7;
	sa.service_name[1] = 9;
	sa.service_name[2] = 3;
	sa.service_name_len = 3;

	fprintf(stderr, "%s:%d\n", __func__, __LINE__);
	bind(fd, (struct sockaddr*)&sa, sizeof(sa));
	fprintf(stderr, "%s:%d\n", __func__, __LINE__);

	return 0;
}

int main()
{
	fprintf(stderr, "%s:%d\n", __func__, __LINE__);
	fd = socket(AF_NFC, 0x2ul, 0x1ul);
	pthread_t th;
	pthread_create(&th, 0, thr, 0);
	struct sockaddr_nfc_llcp sa;
	int len = sizeof(sa);
	getsockname(fd, (struct sockaddr*)&sa, &len);
	fprintf(stderr, "%s:%d\n", __func__, __LINE__);

	return 0;
}
