# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2021,2022,2025 Krzysztof Kozlowski
# Author: Krzysztof Kozlowski <krzk@kernel.org>
---
- hosts: buildbot_builders
  roles:
    - hardened
    - sshd
    - tunnel
    - buildbot-git-mirror
    - buildbot-builder

- hosts: buildbot_artifact_storage
  roles:
    - buildbot-build-storage

- hosts: buildbot_masters
  roles:
    - buildbot-git-mirror
    - buildbot-upload-dest
