---
- hosts: buildbot_builders
  roles:
    - hardened
    - sshd
    - tunnel
    - buildbot-git-mirror
    - buildbot-builder

- hosts: buildbot_masters
  roles:
    - buildbot-git-mirror
    - buildbot-upload-dest
