#!/bin/bash
#
# Copyright (c) 2020 Krzysztof Kozlowski
# Author: Krzysztof Kozlowski <k.kozlowski.k@gmail.com>
#                             <krzk@kernel.org>
#
# SPDX-License-Identifier: GPL-2.0
#

apply_msg_id() {
	local msg_id="$1"
	local options="$2"

	test -n "$msg_id" || return 0

	echo "Applying ${msg_id}"
	echo "b4 am --apply-cover-trailers --outdir - --add-link --cherry-pick _ ${msg_id} | git am $options"
	b4 am --apply-cover-trailers --outdir - --add-link --cherry-pick _ "${msg_id}" | git am $options
	exit $?
}

SOB=""
if [ "$1" == "--si" ]; then
	SOB="--signoff"
fi

while IFS= read -r line; do
	if [[ "$line" == "Message-Id: "* ]]; then
		apply_msg_id  "${line#Message-Id: }" "$SOB"
	elif [[ "$line" == "Message-Id:" ]]; then
		read -r line
		if [[ "$line" == "<"* ]] || [[ "$line" == " <"* ]] || [[ "$line" == "	<"* ]]; then
			apply_msg_id "$line" "$SOB"
		fi
	elif [[ "$line" == "Message-ID: "* ]]; then
		apply_msg_id "${line#Message-ID: }" "$SOB"
	elif [[ "$line" == "Message-ID:" ]]; then
		read -r line
		if [[ "$line" == "<"* ]] || [[ "$line" == " <"* ]] || [[ "$line" == "	<"* ]]; then
			apply_msg_id "$line" "$SOB"
		fi
	fi
done

echo "Message ID not found"
