#!/bin/bash
#
# Copyright (c) 2023 Krzysztof Kozlowski
# Author: Krzysztof Kozlowski <k.kozlowski.k@gmail.com>
#                             <krzk@kernel.org>
#
# SPDX-License-Identifier: GPL-2.0
#
# Installation:
# 1. Copy to .git/hooks/post-commit and .git/hooks/post-applypatch
# 2. Adjust paths to vanilla (pure Linus' tree) and tools directory
#

TOOLS_DIR="$HOME/dev/tools/linux/"
VANILLA_LINUS_DIR="../vanilla/"

echo -n "[Checking commit] "
git --no-pager log --format="%C(auto) %h %s" -n1
echo "[Checkpatch] "

git show --format=email HEAD | ./scripts/checkpatch.pl --strict --quiet
test $? -eq 0 && echo "OK"
echo

echo "[Signed-off-by] "
${TOOLS_DIR}verify_signedoff.sh HEAD^..HEAD
test $? -eq 0 && echo "OK"
echo

echo "[Fixes] "
${TOOLS_DIR}verify_fixes.sh "$VANILLA_LINUS_DIR" HEAD^..HEAD
test $? -eq 0 && echo "OK"
echo

exit 0
