# Copyright (C) 2021-2022 Linaro Ltd
# Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
#                             <krzk@kernel.org>
#
# SPDX-License-Identifier: GPL-2.0

version: 1
name: mem-ctrl
description: Linux memory controllers builds and tests
jobs:
  - name: Defconfig arm
    builds:
      - {target_arch: arm,       toolchain: gcc-10,   kconfig: multi_v7_defconfig}
      - {target_arch: arm,       toolchain: gcc-10,   kconfig: [multi_v7_defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}
    test: {device: qemu-armv7,   tests: [kunit, kselftest-gpio, kselftest-ipc, kselftest-rtc, ltp-smoke]}

  - name: Defconfig arm64
    builds:
      - {target_arch: arm64,     toolchain: gcc-10,   kconfig: defconfig}
      - {target_arch: arm64,     toolchain: clang-11, kconfig: defconfig}
      - {target_arch: arm64,     toolchain: gcc-10,   kconfig: [defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}
      - {target_arch: arm64,     toolchain: clang-11, kconfig: [defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}
    test: {device: qemu-arm64,   tests: [kunit, kselftest-gpio, kselftest-ipc, kselftest-rtc, ltp-smoke]}

  - name: Defconfig i386
    builds:
      - {target_arch: i386,      toolchain: gcc-10,   kconfig: defconfig}
      - {target_arch: i386,      toolchain: clang-11, kconfig: defconfig}
      - {target_arch: i386,      toolchain: gcc-10,   kconfig: [defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}
      - {target_arch: i386,      toolchain: clang-11, kconfig: [defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}
    test: {device: qemu-i386, tests: [kunit, kselftest-gpio, kselftest-ipc, kselftest-rtc, ltp-smoke]}

  - name: Defconfig mips
    builds:
      - {target_arch: mips,      toolchain: gcc-10,   kconfig: defconfig}
      - {target_arch: mips,      toolchain: gcc-10,   kconfig: malta_defconfig}
        #- {target_arch: mips,    toolchain: clang-11, kconfig: defconfig}
      - {target_arch: mips,      toolchain: gcc-10,   kconfig: [defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}
    test: {device: qemu-mips64,  tests: [kunit, kselftest-gpio, kselftest-ipc, kselftest-rtc, ltp-smoke]}

  - name: Defconfig powerpc
    builds:
      - {target_arch: powerpc,   toolchain: gcc-10,   kconfig: defconfig}
        #- {target_arch: powerpc, toolchain: clang-11, kconfig: defconfig}
      - {target_arch: powerpc,   toolchain: gcc-10,   kconfig: [defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}

  - name: Defconfig riscv
    builds:
      - {target_arch: riscv,     toolchain: gcc-10,   kconfig: defconfig}
        #- {target_arch: riscv,   toolchain: clang-11, kconfig: defconfig}
      - {target_arch: riscv,     toolchain: gcc-10,   kconfig: [defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}
    test: {device: qemu-riscv64, tests: [kunit, kselftest-gpio, kselftest-ipc, kselftest-rtc, ltp-smoke]}

  - name: Defconfig s390
    builds:
      - {target_arch: s390,      toolchain: gcc-10,   kconfig: defconfig}
        #- {target_arch: s390,    toolchain: clang-11, kconfig: defconfig}
      - {target_arch: s390,      toolchain: gcc-10,   kconfig: [defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}

  - name: Defconfig sparc
    builds:
      - {target_arch: sparc,     toolchain: gcc-10,   kconfig: sparc32_defconfig}
        #- {target_arch: sparc,   toolchain: clang-11, kconfig: sparc32_defconfig}
      - {target_arch: sparc,     toolchain: gcc-10,   kconfig: sparc64_defconfig}
        #- {target_arch: sparc,   toolchain: clang-11, kconfig: sparc64_defconfig}
      - {target_arch: sparc,     toolchain: gcc-10,   kconfig: [sparc32_defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}
      - {target_arch: sparc,     toolchain: gcc-10,   kconfig: [sparc64_defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}

  - name: Defconfig x86_64
    builds:
      - {target_arch: x86_64,    toolchain: gcc-10,   kconfig: defconfig}
      - {target_arch: x86_64,    toolchain: clang-11, kconfig: defconfig}
      - {target_arch: x86_64,    toolchain: gcc-10,   kconfig: [defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}
      - {target_arch: x86_64,    toolchain: clang-11, kconfig: [defconfig,
         "CONFIG_COMPILE_TEST=y", "CONFIG_OF=y", "CONFIG_SRAM=y", "CONFIG_MEMORY=y",
         "CONFIG_PM_DEVFREQ=y", "CONFIG_ARM_PL172_MPMC=y", "CONFIG_ATMEL_SDRAMC=y",
         "CONFIG_ATMEL_EBI=y", "CONFIG_BRCMSTB_DPFE=y", "CONFIG_BT1_L2_CTL=y",
         "CONFIG_TI_AEMIF=y", "CONFIG_TI_EMIF=y", "CONFIG_OMAP_GPMC=y",
         "CONFIG_TI_EMIF_SRAM=y",
         "CONFIG_FPGA=y", "CONFIG_FPGA_DFL=y", "CONFIG_FPGA_DFL_EMIF=y",
         "CONFIG_MVEBU_DEVBUS=y",
         "CONFIG_FSL_CORENET_CF=y", "CONFIG_FSL_IFC=y", "CONFIG_JZ4780_NEMC=y",
         "CONFIG_MTK_SMI=y", "CONFIG_DA8XX_DDRCTL=y", "CONFIG_PL353_SMC=y",
         "CONFIG_RENESAS_RPCIF=y", "CONFIG_STM32_FMC2_EBI=y", "CONFIG_SAMSUNG_MC=y",
         "CONFIG_EXYNOS5422_DMC=y", "CONFIG_EXYNOS_SROM=y", "CONFIG_TEGRA_MC=y",
         "CONFIG_TEGRA20_EMC=y", "CONFIG_TEGRA30_EMC=y", "CONFIG_TEGRA124_EMC=y",
         "CONFIG_TEGRA210_EMC_TABLE=y", "CONFIG_TEGRA210_EMC=y"]}
    test: {device: qemu-x86_64, tests: [kunit, kselftest-gpio, kselftest-ipc, kselftest-rtc, ltp-smoke]}
