# Copyright (C) 2021-2022 Linaro Ltd
# Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
#                             <krzk@kernel.org>
#
# SPDX-License-Identifier: GPL-2.0

version: 1
name: samsung
description: Samsung Exynos SoC builds and tests
jobs:
  - name: Exynos ARMv7 - boot
    builds:
      - {target_arch: arm,       toolchain: gcc-10,   kconfig: multi_v7_defconfig}
    test: {device: qemu-armv7,   tests: [kunit, kselftest-gpio, kselftest-ipc, kselftest-rtc, ltp-smoke]}

  - name: Exynos, S3C, S5P ARMv7 - build
    builds:
      - {target_arch: arm,       toolchain: gcc-10,   kconfig: exynos_defconfig}
      - {target_arch: arm,       toolchain: gcc-10,   kconfig: mini2440_defconfig}
      - {target_arch: arm,       toolchain: gcc-10,   kconfig: multi_v7_defconfig}
      - {target_arch: arm,       toolchain: gcc-10,   kconfig: s3c2410_defconfig}
      - {target_arch: arm,       toolchain: gcc-10,   kconfig: s3c6400_defconfig}
      - {target_arch: arm,       toolchain: gcc-10,   kconfig: s5pv210_defconfig}
      - {target_arch: arm,       toolchain: gcc-10,   kconfig: tct_hammer_defconfig}

  - name: Exynos ARMv8 - boot
    builds:
      - {target_arch: arm64,     toolchain: gcc-10,   kconfig: defconfig}
      - {target_arch: arm64,     toolchain: clang-11, kconfig: defconfig}
    test: {device: qemu-arm64,   tests: [kunit, kselftest-gpio, kselftest-ipc, kselftest-rtc, ltp-smoke]}

  - name: Rest - build
    builds:
      - {target_arch: arm64,     toolchain: gcc-10, kconfig: allyesconfig}
      - {target_arch: arm64,     toolchain: gcc-10, kconfig: allmodconfig}
